# Generated by Django 5.2.7 on 2025-11-02 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Properties',
            new_name='Property',
        ),
    ]
